### ISSUE TITLE
Update to discord.js v13

### ISSUE THREAD

**Issue by NotSoMik** [SimonLeclere/discord-hangman#18]
Hello, im having issues using this version of discordjs. Can you please update this hangman system to discord.js v13 so I can use it. 🥰

**Comment by Spongecade** [comment]
I'm going to be the one updating this project. But unfortunately, My PC broke and I will be finding a replacement. So unless @SimonLeclere updates this project, this will take some time...

**Comment by SimonLeclere** [comment]
Hey @rufy545, I saw your message and I started to upgrade the module to v13. I didn't answer you right away because I was quite busy (and then I forgot --') sorry ;)

Unfortunately I'm in my back-to-school period so I can't give you exact indications on how long it will take but don't worry I'm working on it!

Oh and @Spongecade, my condolences for your pc ;) When you get a new one, don't hesitate to continue your pullrequest!

**Comment by NotSoMik** [comment]
Oh cool, thanks for your reply 🥰
