### ISSUE TITLE
Doesnt work with djs v13

### ISSUE THREAD

**Issue by Phydose** [SimonLeclere/discord-hangman#19]
The package doesnt work with djs v13

**Comment by SimonLeclere** [comment]
Hey, indeed the package is not updated for v13 for the moment. I'm quite busy with my studies and my personal life and I don't have much time to work on it. @Spongecade had mentioned that he was motivated to update the module but I haven't heard from him since. If you feel able to do so, feel free to make a pull request ;)

**Comment by Spongecade** [comment]
I've also been busy with school. But I am determined to update DH when I get my new computer (which should happen in a few weeks).

**Comment by Spongecade** [comment]
Hey!

I know it's been a while... I've had my new computer for about a month now but I've been sidetracked with school and have exams coming up in a few weeks. I am committed to updating this to Discordjs v13. All of the code, is on the old computer but I'm in the process of transferring my files to the new computer. I'll have to catch up on documentation and the code. With all of this being said, it may take a little while longer to have Discord Hangman updated but I'm eager to do so!

**Comment by SimonLeclere** [comment]
Thank you very much ! Honestly, I'm also in a exams period and haven't really taken the time to work on discord-hangman. If you need help don't hesitate to contact me on discord !

**Comment by Spongecade** [comment]
Ok, thank you!

**Comment by SimonLeclere** [comment]
Done (with some delay sorry guys)
